keepalive: Add inspect command to disable NVMe keepalives (#2789)
Add `vm/nvme_keepalive_mode` inspect node shows the current status, but
can be updated through `ohcldiag-dev`:

```
C:\openvmm>ohcldiag-dev.exe uhdiag.sock i vm/nvme_keepalive_mode
"enabled"

C:\openvmm>ohcldiag-dev.exe uhdiag.sock i vm/nvme_keepalive_mode -u disabled
"disabled"

C:\openvmm>ohcldiag-dev.exe uhdiag.sock i vm/nvme_keepalive_mode
"disabled"

C:\openvmm>ohcldiag-dev.exe uhdiag.sock i vm/nvme_keepalive_mode -u enabled
"enabled"

C:\openvmm>ohcldiag-dev.exe uhdiag.sock i vm/nvme_keepalive_mode
"enabled"

C:\openvmm>ohcldiag-dev.exe uhdiag.sock i vm/nvme_keepalive_mode -u blah
Error: update error: Invalid keepalive config: blah
```

Add a test for this in `openhcl_servicing.rs` that verifies that the
keepalive can be disabled, and servicing completes successfully.

(cherry picked from commit 458c1282da74cf254ec2fd031d32bad0d75b6ac2)